import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const startups = [
  // ── ORIGINAL 8 ──────────────────────────────────────────────────────────────

  {
    name: "Quibi",
    tagline: "Premium short-form video for mobile, built for the on-the-go generation.",
    industry: "Streaming",
    foundedYear: 2018,
    closedYear: 2020,
    story: `We raised $1.75 billion before a single user downloaded the app. That should have been the first warning sign — not because the money was bad, but because it insulated us from reality for far too long.\n\nQuibi was born from a genuinely interesting insight: people consume media in small bursts throughout the day — waiting for coffee, commuting, standing in line. We wanted to build the best 10-minute content experience in the world. Jeffrey and I had decades of Hollywood and Silicon Valley experience combined. We hired world-class talent. We signed deals with Spielberg, Idris Elba, Jennifer Lopez.\n\nWe launched April 6, 2020. Six days after California's COVID-19 lockdown began. In a world where nobody was commuting, waiting in lines, or stealing moments away from home — the exact moments we were designed for had vanished. People were watching Netflix on 65-inch TVs, not Quibi on a phone screen.\n\nBut I'd be lying if I blamed only COVID. The product had deeper problems. We launched without Chromecast or AirPlay support, so you couldn't watch Quibi on your TV even if you wanted to. We couldn't share clips — you couldn't send someone a 30-second moment the way you share a TikTok. Social virality was architecturally impossible. And critically, nobody could screenshot our content, which killed press coverage and organic buzz stone dead.\n\nWe had no free tier. $4.99/month with ads or $7.99 without — for an app nobody had heard of six months ago. We converted only 8% of trial users. The number haunts me.\n\nWe shut down October 2020. Six months after launch. We returned over $350 million to investors.`,
    whatFailed: `PMF mismatch was the core issue. We built for a context — commuting, on-the-go micro-moments — that COVID eliminated overnight. But even pre-COVID, the insight was fragile. People already had Instagram Reels, YouTube, TikTok. We didn't have a truly differentiated product, just more expensive content in the same format.\n\nThe no-screenshot, no-sharing architecture was a catastrophic product decision. Virality is the only cost-effective distribution for consumer apps in 2020. We built a premium walled garden when the market had already voted for open, shareable social content.\n\nWe launched at $4.99/month with no free tier and no brand recognition. That's VC pitch deck logic, not consumer psychology.`,
    lessonsLearned: `Validate the core insight in the cheapest way possible before raising. We raised $1.75B on a thesis. A $500k prototype could have tested whether commuters actually wanted premium short-form.\n\nNever build a consumer app that can't be shared. Virality is not optional anymore. Social proof and shareability are table stakes.\n\nA great team with great capital can still build the wrong thing. Pedigree doesn't substitute for product-market fit.`,
    peakMrr: 400000,
    teamSize: 200,
    totalRaised: 1750000000,
    aiRootCause: "PMF mismatch — built for on-the-go consumption in an era of lockdowns, with architecture that made social virality structurally impossible.",
    aiFactors: JSON.stringify(["Launched during COVID when the core use-case (commuting, on-the-go) was eliminated", "No sharing/screenshot functionality killed organic virality", "Launched without TV casting despite competing with living-room streaming", "High-priced paywall with no free tier before establishing brand trust", "Overcapitalized too early — $1.75B insulated team from market feedback"]),
    aiTags: JSON.stringify(["PMF mismatch", "Market timing"]),
    aiVerdict: "Quibi is a textbook case of capitalizing ahead of validation. The mobile short-form insight was real but the execution assumed a pre-pandemic world that vanished on launch day. The product's anti-sharing architecture compounded the problem by eliminating the only scalable distribution channel available to a new consumer brand.",
  },
  {
    name: "Theranos",
    tagline: "One tiny drop. Hundreds of tests. The future of diagnostics.",
    industry: "Healthtech",
    foundedYear: 2003,
    closedYear: 2018,
    story: `I started Theranos at 19 with a vision I believed completely: that the fear of needles and the cost of blood tests were keeping people from catching diseases early, and that was killing them. I still believe that vision was right. The execution was fraud.\n\nFor the first decade, we raised money on promises and projections. The Edison device — our proprietary miniaturized analyzer — never worked the way we claimed. We told investors, partners, and eventually Walgreens that we could run 200+ tests from a finger-prick of blood with lab-accurate results. We could not.\n\nBy 2013 we were running the vast majority of our tests on commercial Siemens machines — the same analyzers every other lab uses — while showing customers a proprietary-looking interface. We diluted finger-prick samples to run on machines designed for venous blood, introducing errors we never disclosed. We knew results were unreliable in categories like HIV, cancer markers, and cardiac troponin.\n\nReal patients made real medical decisions based on those results.\n\nThe WSJ investigation in 2015 began unraveling everything. FDA inspections followed. CMS inspections. The lab director resigned. By 2018 I was indicted. The company was dissolved.\n\nI caused harm to patients who trusted us. That is the thing I cannot undo.`,
    whatFailed: `Regulatory fraud is the bluntest answer. We made claims to regulators, partners, and patients that we knew were false. That's not a startup mistake — it's a crime.\n\nBut underneath the fraud was a product that never worked. The core science — running hundreds of validated clinical tests from a micro-sample of capillary blood — may be achievable someday. It was not achievable in 2003, 2010, or 2015. We built a company around a scientific claim we couldn't substantiate and chose deception over transparency every time the gap became visible.`,
    lessonsLearned: `Never let vision outrun honesty. When your product doesn't work, the answer is to go back to the science, not to obscure the gap with better storytelling.\n\nIn regulated industries — especially healthcare — regulatory compliance is not a moat. It's the floor.\n\nBoards need domain expertise, not only prestige. A single clinical pathologist on the board might have asked the right questions in 2008.`,
    peakMrr: null,
    teamSize: 800,
    totalRaised: 945000000,
    aiRootCause: "Execution fraud — the core technology never worked, and leadership chose systematic deception over transparency, resulting in patient harm and criminal prosecution.",
    aiFactors: JSON.stringify(["Core technology was never scientifically validated", "Leadership actively concealed product failures from regulators, partners, and patients", "Board lacked clinical or laboratory science expertise", "Regulatory environment treated as adversary rather than accountability framework", "Culture of secrecy prevented internal whistleblowers from surfacing problems"]),
    aiTags: JSON.stringify(["Execution", "Regulatory"]),
    aiVerdict: "Theranos is not a startup failure story — it is a fraud case with a startup wrapper. The underlying mission was genuine but the moment the technology fell short, the choice was made to deceive rather than rebuild.",
  },
  {
    name: "Juicero",
    tagline: "The freshest cold-pressed juice. Delivered. Pressed at home.",
    industry: "Hardware / Food",
    foundedYear: 2013,
    closedYear: 2017,
    story: `We built a $699 wi-fi connected cold-press juicer backed by $120 million in Silicon Valley venture capital. I thought we were building the Nespresso of juice — a premium appliance with recurring pack revenue. Instead we became the symbol of peak Silicon Valley absurdity.\n\nThe design was genuinely beautiful. We used the same tolerances as aerospace components. The machine could exert four tons of pressure. Every pack was RFID-chipped and connected to our servers to verify freshness and authenticity.\n\nIn April 2017, a Bloomberg journalist filmed themselves squeezing a Juicero pack by hand and getting the same juice as the machine produced. The video went viral. Within 24 hours we were a global punchline.\n\nThe machine that cost more than an iPhone and required wi-fi to operate... was unnecessary. We shut down in September 2017, five months after the Bloomberg video.`,
    whatFailed: `PMF mismatch, definitionally. We built a $700 machine for a behavior (daily fresh juice at home) that the market hadn't validated at any price point, let alone $700.\n\nThe Bloomberg video didn't destroy Juicero. It revealed what Juicero had always been: a beautifully engineered answer to a question nobody asked.`,
    lessonsLearned: `Solve a real problem first. Then engineer the solution. We inverted this.\n\nNever build a moat around artificial lock-in. If your value proposition disappears when a journalist squeezes your product bag by hand, you don't have a value proposition.`,
    peakMrr: 50000,
    teamSize: 120,
    totalRaised: 120000000,
    aiRootCause: "PMF mismatch — engineered a premium hardware-subscription product for a behavior with no validated consumer demand.",
    aiFactors: JSON.stringify(["No validated consumer demand for home cold-press juicing at $700+", "Hardware + mandatory subscription created double friction at purchase", "Artificial dependency on machine exposed as unnecessary by a single viral video", "Capital availability allowed team to build without market validation"]),
    aiTags: JSON.stringify(["PMF mismatch", "Cash flow"]),
    aiVerdict: "Juicero built with exceptional engineering quality toward a problem consumers hadn't articulated and wouldn't pay to solve. The Bloomberg squeeze video was not the cause of death — it was the autopsy revealing a patient who was never viable.",
  },
  {
    name: "MoviePass",
    tagline: "See all the movies you want in theaters for one low monthly price.",
    industry: "Subscriptions / Entertainment",
    foundedYear: 2011,
    closedYear: 2019,
    story: `In August 2017 we dropped our price from $50/month to $9.95/month — all the movies you can see, unlimited, in real theaters. Within 48 hours our servers crashed. We gained 150,000 subscribers in a single day. We thought we had won.\n\nWe were paying full ticket price to theaters for every movie our subscribers saw. At $9.95/month, a subscriber who saw two movies covered our costs. Anyone who saw three or more cost us money. Our most engaged users — the people who loved us the most — were our biggest liabilities.\n\nThe thesis was data monetization and eventually theater revenue share deals. But the unit economics never worked. At peak, we had 3 million subscribers burning through cash faster than any data or partnership deal could rescue.\n\nBy 2019 we couldn't process payments. The service went dark. We filed for bankruptcy shortly after.`,
    whatFailed: `The unit economics were broken from day one of the $9.95 price point. We knew this. The bet was that we'd get to scale and leverage before we ran out of cash, and that data and partnership revenue would bridge the gap. We lost the race.\n\nYou cannot outrun broken unit economics with scale. Scale makes broken unit economics worse, not better.`,
    lessonsLearned: `Never build a subscription model where your most loyal users are your biggest losses. Engagement and revenue must be aligned.\n\nData monetization is a hard, slow business. It cannot be a bridge over a burning financial structure.`,
    peakMrr: 30000000,
    teamSize: 75,
    totalRaised: 68000000,
    aiRootCause: "Cash flow collapse — unit economics were structurally inverted from launch, with subscriber engagement accelerating losses.",
    aiFactors: JSON.stringify(["Priced subscription below cost of a single movie ticket while paying full retail per viewing", "Data monetization was theoretical future revenue used to justify present losses", "Theaters had no incentive to partner — MoviePass cannibalized their per-ticket revenue", "Rapid subscriber growth amplified cash burn before any model fix was possible"]),
    aiTags: JSON.stringify(["Cash flow", "Execution"]),
    aiVerdict: "MoviePass collapsed because the core product was structurally unprofitable by design. When scale arrived, it accelerated the bankruptcy rather than solving it.",
  },
  {
    name: "Vine",
    tagline: "See and share life in motion. Six seconds at a time.",
    industry: "Social / Video",
    foundedYear: 2012,
    closedYear: 2017,
    story: `Twitter acquired us for $30 million before we'd even launched. January 2013 we went live. By summer we were the fastest-growing app in the App Store. Six-second looping videos. The constraint was the creativity.\n\nAt our peak we had 200 million users. We launched careers. King Bach, Brittany Furlan, Logan Paul — these were Vine-native celebrities with audiences Twitter's own platform couldn't replicate.\n\nAnd then Instagram launched 15-second video. Then Instagram went to 60 seconds. Then Facebook video. Then YouTube ramped creator monetization.\n\nWe did nothing. Twitter was distracted — three CEOs in three years. Vine got no resources, no monetization for creators, no advertising product. Creators left. The audience followed.\n\nTwitter announced the shutdown in October 2016. We went dark in January 2017.`,
    whatFailed: `We failed to monetize creators. This is the whole story. TikTok learned this lesson from our corpse — they built creator funds into the product from the start.\n\nBeing inside Twitter was our original lifeline and our eventual death sentence. We were always competing for engineering resources with Twitter's own crisis.`,
    lessonsLearned: `Creator platforms live and die by creator economics. If you build your value on user-generated content, monetizing those users is not optional — it's existential.\n\nBeing acquired early by a distracted parent company is often worse than staying independent.`,
    peakMrr: null,
    teamSize: 200,
    totalRaised: 30000000,
    aiRootCause: "Competition and pivot failure — failed to build creator monetization as Instagram and YouTube cloned the format with better economics.",
    aiFactors: JSON.stringify(["No creator monetization program allowed competitors to poach top creators", "Twitter's internal dysfunction starved Vine of engineering investment", "Core format (6-second video) was easily cloned — no defensible moat", "Parent company acquisition eliminated independent strategic decision-making"]),
    aiTags: JSON.stringify(["Competition", "Pivot failure"]),
    aiVerdict: "Vine created a new creative medium and then failed to own it. By not monetizing the creators who built the platform's value, Vine left the door open for capitalized competitors to purchase their way into the creator base.",
  },
  {
    name: "Jawbone",
    tagline: "Wearable wellness. Track your sleep, steps, and life.",
    industry: "Wearables / Hardware",
    foundedYear: 2010,
    closedYear: 2017,
    story: `We spent 17 years building audio hardware before pivoting to wearables in 2010. The UP fitness tracker was our bet on the quantified self movement. We raised over $900 million — more than any consumer wearable company in history.\n\nThe first UP band launched in 2011 and failed catastrophically. The product had a fundamental hardware defect — the bands stopped working after a few weeks of use. We did a full recall and refund. That recall cost us tens of millions and destroyed our brand momentum.\n\nWe kept trying. UP2, UP3, UP4. Each generation was better hardware. But Fitbit was faster, cheaper, and already synonymous with fitness tracking. Apple Watch launched in 2015 and reframed the entire wearable category.\n\nWe filed for liquidation in 2017 with hundreds of millions in outstanding debts.`,
    whatFailed: `The hardware recall in 2011 was never fully recovered from — not financially, and not brand-wise. We burned through cash and credibility simultaneously.\n\nThe competitive dynamics of wearables were brutal. Fitbit dominated the mass market. Apple owned the premium end. There was no sustainable position in between.`,
    lessonsLearned: `Hardware margins are thin and unforgiving. A recall in year one of a hardware company is often fatal.\n\nCapital raised is not a proxy for business viability. $900M gave us years of runway without forcing us to face the fundamental competitive problem.`,
    peakMrr: 700000,
    teamSize: 900,
    totalRaised: 900000000,
    aiRootCause: "Cash flow destruction through hardware recall followed by competitive squeeze — unable to find defensible market position.",
    aiFactors: JSON.stringify(["Launch recall of UP band wiped early revenue and brand trust", "Overcapitalization ($900M) enabled years of spending without forcing viable business model", "Apple Watch redefined the premium wearable category", "Fitbit occupied the mass market with faster iteration cycles", "Failed pivot to enterprise/medical market came too late"]),
    aiTags: JSON.stringify(["Cash flow", "Competition"]),
    aiVerdict: "Jawbone is a cautionary tale about the interaction between hardware fragility and competitive dynamics. With $900 million raised, the company had resources to survive for years but never the clarity to pick a winnable competitive position.",
  },
  {
    name: "Rdio",
    tagline: "The music streaming service built for music lovers.",
    industry: "Music Streaming",
    foundedYear: 2008,
    closedYear: 2015,
    story: `We launched before Spotify came to the US. Our design was widely considered superior. Music press loved us. Early adopters loved us.\n\nWhen Spotify launched in the US in July 2011, everything changed. They had the major labels locked up with better deals. They had a free tier. We had a 14-day trial and then $4.99/month minimum.\n\nThe free tier is what killed us. Music listeners are highly price-sensitive — they've been conditioned since Napster to expect music for free. Spotify's ad-supported free tier captured the top of the funnel at massive scale.\n\nApple Music launched in 2015. We were already declining. Pandora acquired our technology assets for $75 million in November 2015.`,
    whatFailed: `Competition from better-capitalized and better-positioned competitors. Spotify had superior label deals and a free tier we couldn't match financially. Apple had pre-existing customer relationships and platform distribution we could never replicate.\n\nIn music streaming, content licensing deals are the actual product. Technology is a display layer. We had good technology. We didn't have good enough deals.`,
    lessonsLearned: `Being early in a market doesn't guarantee survival — it just means you educate the market for the competitor with better resources.\n\nIn zero-sum platform wars, the free tier is not a growth hack — it's a survival mechanism.`,
    peakMrr: 3000000,
    teamSize: 200,
    totalRaised: 125000000,
    aiRootCause: "Competition and market timing — faced Spotify's superior label deals and free tier, and Apple's platform distribution advantage.",
    aiFactors: JSON.stringify(["No free ad-supported tier limited top-of-funnel to price-committed users only", "Spotify's US launch with superior licensing deals captured the mass market", "Music streaming requires hundreds of millions of subscribers for economic viability", "Apple Music's entry with 500M iTunes accounts created insurmountable distribution advantage"]),
    aiTags: JSON.stringify(["Competition", "Market timing"]),
    aiVerdict: "Rdio built the right product for a market where distribution and licensing — not design — determined survival. In a commodity streaming market, the company with the best economics wins.",
  },
  {
    name: "Yik Yak",
    tagline: "Anonymous local social. See what people around you are saying.",
    industry: "Social",
    foundedYear: 2013,
    closedYear: 2017,
    story: `We built Yik Yak on a dorm room insight: what if Twitter was anonymous and hyperlocal? College campuses went insane for us. Fall 2013 we launched at Furman University and within weeks had spread virally to over 150 campuses. We raised $73.5 million on that momentum.\n\nAnd then the problems started. Anonymous platforms with no accountability are magnets for the worst behavior. Bullying, harassment, bomb threats. Schools started banning us. The media covered us primarily as a vehicle for cyberbullying.\n\nIn 2016 we made the fatal product decision: we added usernames. We thought it would reduce harassment. Instead, it destroyed our core value proposition. We had become Twitter. Nobody needed another Twitter.\n\nSquare acquired our engineering team for $1 million in 2017.`,
    whatFailed: `Anonymity without accountability is an unsustainable product design in social media. The very feature that made Yik Yak magical — no identity — made it a harbor for harassment and threats.\n\nThe username addition in 2016 was the death blow. We removed anonymity to solve a safety problem, but anonymity was the only thing differentiating us from every other social app.`,
    lessonsLearned: `Design for safety from the start. Anonymous platforms require proactive safety architecture, not reactive moderation bolted on after launch.\n\nWhen a safety fix requires removing your core differentiating feature, the product was probably not viable long-term from the beginning.`,
    peakMrr: null,
    teamSize: 75,
    totalRaised: 73500000,
    aiRootCause: "Regulatory and PMF mismatch — anonymous platform design made harassment structurally inevitable, and removing anonymity eliminated the product's entire value proposition.",
    aiFactors: JSON.stringify(["Anonymous platform design enabled harassment with no systemic solution", "School and law enforcement pressure forced compliance costs before broader PMF", "Adding usernames removed the only differentiating feature from existing platforms", "College campus concentration created audience ceiling with no path to broader users", "Brand association with cyberbullying made mainstream advertiser monetization impossible"]),
    aiTags: JSON.stringify(["Regulatory", "PMF mismatch"]),
    aiVerdict: "Yik Yak's failure was architectural from the beginning. Anonymity without accountability generates toxic behavior at scale. The founders' attempted fix was the correct safety decision and the terminal product decision simultaneously.",
  },

  // ── DOT-COM ERA ──────────────────────────────────────────────────────────────

  {
    name: "Pets.com",
    tagline: "Because pets can't drive. Everything your pet needs, delivered.",
    industry: "E-commerce / Pet Supply",
    foundedYear: 1998,
    closedYear: 2000,
    story: `We spent $11.8 million on a single Super Bowl commercial in January 2000. The sock puppet mascot was beloved. We had brand recognition that most companies spend decades building. We had it in under two years.\n\nWhat we didn't have was a business model that worked.\n\nSelling heavy bags of dog food and cat litter online and shipping them to consumers at a discount was mathematically impossible. The average bag of dog food cost us more to ship than we charged for it, before accounting for the cost of the product itself. We were offering free shipping on items that weighed 30 pounds. We were selling $100 worth of products for $75 and losing another $30 on shipping.\n\nWe raised $82.5 million in our February 2000 IPO at $11/share. By November we were trading at 19 cents. We shut down nine months after going public.\n\nThe sock puppet appeared in our liquidation sale ad. Even at the end, the brand was stronger than the business.`,
    whatFailed: `The fundamental unit economics were broken and nobody — not us, not our VCs, not the public markets — ran the numbers hard enough before the IPO. Selling commoditized, heavy, low-margin physical goods online in 1998 required logistics infrastructure that didn't exist and margins that were impossible given the product category.\n\nWe focused on brand and growth. We should have focused on gross margin per order. The two were incompatible, and we chose the wrong one.`,
    lessonsLearned: `Gross margin is not a finance metric — it's a survival metric. Every business must understand what it earns per transaction before scaling anything.\n\nBrand is amplification, not compensation. A beloved brand amplifies a good business. It cannot rescue a broken one.\n\nThe "get big fast" strategy only works if getting big makes the economics better. In our case, getting bigger made the losses larger.`,
    peakMrr: 650000,
    teamSize: 320,
    totalRaised: 82500000,
    aiRootCause: "Cash flow collapse from structurally negative unit economics — selling and shipping heavy, low-margin goods below cost with no path to profitability at any scale.",
    aiFactors: JSON.stringify(["Negative gross margins on every order due to heavy goods + free shipping + discounted pricing", "IPO capital used to fund operations rather than fix underlying business model", "$11.8M Super Bowl ad spend without unit economics to support customer LTV", "Infrastructure for low-cost physical goods delivery did not exist in 1998", "Board and investors prioritized GMV growth over per-transaction economics"]),
    aiTags: JSON.stringify(["Cash flow", "PMF mismatch"]),
    aiVerdict: "Pets.com is the canonical example of dot-com era economics: brand-first, economics-never. The sock puppet mascot outlasted the company because it was the only part of the business that actually worked. The model was broken at the unit level before the first order shipped.",
  },
  {
    name: "Webvan",
    tagline: "Grocery delivery in 30 minutes. Everything from your supermarket, delivered.",
    industry: "Grocery Delivery",
    foundedYear: 1996,
    closedYear: 2001,
    story: `We wanted to reinvent how America bought groceries. Not incrementally — completely. We built massive automated distribution centers in every major city simultaneously. We bought a fleet of delivery vans. We hired thousands of employees. We signed a $1 billion contract with Bechtel to build 26 warehouses.\n\nWe never proved the model worked in a single city first.\n\nAt our peak we were delivering groceries in 10 cities, losing money in all of them. Analysts estimated we lost roughly $130 on every order delivered. We burned through nearly $1 billion in capital — the most of any dot-com era startup.\n\nIn June 2001 we filed for bankruptcy, laying off 2,000 employees. The warehouses were auctioned off. Amazon eventually bought some of our technology assets and used them to build Amazon Fresh — the service we should have been.\n\nWe had the right idea, twenty years too early, and we burned all the capital that would have been needed to survive until the market caught up.`,
    whatFailed: `We violated the most basic rule of scaling: prove it works small before building it big. We built the infrastructure for a national operation before proving a single market was profitable.\n\nThe 30-minute delivery window was an engineering achievement and a financial catastrophe. The labor, routing complexity, and van capacity required to deliver a $45 grocery order in 30 minutes meant we could never make money per order.\n\nThe Bechtel contract — $1 billion for 26 warehouses — was signed when we had barely proven the model in a single city. That commitment ended any possibility of a strategic pivot.`,
    lessonsLearned: `Never sign billion-dollar infrastructure contracts before your unit economics are positive. Capital commitments that outlive your cash runway are existential.\n\nThe "winner-take-all" instinct that drove us to expand nationally immediately was wrong for a logistics business. Logistics economics improve with density, not breadth.\n\nOnline grocery delivery is a viable business — but it required 20 more years of smartphone penetration, GPS routing optimization, and consumer behavior change to become so.`,
    peakMrr: 4000000,
    teamSize: 4500,
    totalRaised: 375000000,
    aiRootCause: "Cash flow destruction through premature scaling — built national infrastructure before proving unit economics in a single market, losing $130 per order at scale.",
    aiFactors: JSON.stringify(["Signed $1B Bechtel contract for 26 warehouses before proving model in single city", "Lost $130 per order delivered with no path to contribution-margin positivity", "30-minute delivery window made labor and routing costs structurally unsustainable", "Expanded to 10 cities simultaneously rather than sequentially proving each market", "Infrastructure capital commitments outlived cash runway, eliminating pivot options"]),
    aiTags: JSON.stringify(["Cash flow", "Execution"]),
    aiVerdict: "Webvan had the right product vision and the wrong execution sequence. By building national infrastructure before local proof points, they created capital commitments that made strategic flexibility impossible. Amazon Fresh launched the same concept 12 years later and succeeded by doing the opposite: proving the model in Seattle first.",
  },
  {
    name: "Boo.com",
    tagline: "The global fashion store for the connected generation.",
    industry: "Fashion E-commerce",
    foundedYear: 1999,
    closedYear: 2000,
    story: `We raised $135 million before our site was functional. We hired hundreds of employees across offices in New York, London, Munich, Amsterdam, and Stockholm. We sent press kits in custom Boo.com luggage. We had a virtual shopping assistant named Miss Boo who appeared in 3D on your screen.\n\nMiss Boo was the problem. The site required a broadband connection, a specific browser, JavaScript enabled, and significant patience. In 1999, most internet users had dial-up modems. Miss Boo took minutes to load. Most users left before seeing a single product.\n\nWe spent $25 million on marketing before the site worked properly. We launched six months late. When we finally launched in November 1999, the site crashed under load. Our conversion rate was a fraction of what we needed.\n\nWe filed for bankruptcy in May 2000. Less than a year after launch. The brand and domain were sold for $250,000 — roughly 0.2% of what we raised.`,
    whatFailed: `We built the future of online fashion for a user base that was living in the present. Broadband penetration in 1999 was under 5%. We built a 3D, interactive, multimedia shopping experience for the 5%, then marketed it to everyone.\n\nThe lavish spending — the custom luggage, the international offices, the hundreds of hires before product-market validation — was a cultural choice made possible by easy capital and encouraged by a VC environment rewarding ambition over discipline.`,
    lessonsLearned: `Build for the infrastructure that exists, not the infrastructure you wish existed. We built for a broadband internet that was still five years away for most users.\n\nOperational spending should be gated on product milestones, not funding milestones. We hired and spent as fast as we raised without a functioning product.\n\nLaunching late is survivable. Launching with a broken product that you over-marketed is not.`,
    peakMrr: 200000,
    teamSize: 400,
    totalRaised: 135000000,
    aiRootCause: "PMF mismatch and execution failure — built a multimedia-heavy product requiring broadband for a market that was 95% dial-up, then burned capital before the product functioned.",
    aiFactors: JSON.stringify(["Required broadband connection in 1999 when 95% of internet users had dial-up", "Spent $25M on marketing before site was operational", "Launched 6 months late with a product that still crashed under load", "Maintained offices in 5 countries with 400 employees before proving revenue model", "Custom luggage press kits and Miss Boo 3D avatar were budget sinkholes with no ROI"]),
    aiTags: JSON.stringify(["PMF mismatch", "Cash flow", "Execution"]),
    aiVerdict: "Boo.com spent lavishly to build the wrong product for the wrong infrastructure era. The technology-first approach and refusal to design for actual consumer hardware of 1999 made customer acquisition structurally impossible at the required conversion rates.",
  },
  {
    name: "Kozmo.com",
    tagline: "One-hour delivery of anything. Books, movies, food — whenever you want.",
    industry: "On-Demand Delivery",
    foundedYear: 1998,
    closedYear: 2001,
    story: `We promised to deliver a single candy bar to your door within an hour. For free. In New York City.\n\nThis was not a sustainable business model. We knew it and kept going anyway, believing scale would eventually make it work.\n\nAt our peak we were operating in nine cities, delivering snacks, movies, books, ice cream, and magazines at midnight on a Tuesday. We had our own warehouses, our own courier staff (not gig workers — W-2 employees with benefits), our own distribution infrastructure.\n\nWe raised $280 million. We partnered with Starbucks. We were expanding internationally. We had plans for an IPO that we pulled back at the last minute in 2000 when market conditions shifted.\n\nThe problem was simple: a courier earning $15/hour cannot profitably deliver a $1.50 candy bar. No algorithm was going to fix that. We were subsidizing consumer convenience at massive scale with no minimum order, no delivery fee, and no path to the unit economics becoming positive.\n\nWe shut down in April 2001, laying off 1,100 people.`,
    whatFailed: `The no-delivery-fee, no-minimum-order policy was an ideological choice that made every transaction a money-losing proposition. We were trying to be the most convenient service imaginable without asking whether convenience at this price was deliverable as a business.\n\nGig economy infrastructure didn't exist in 2001 — we had to employ full labor. The comparison to modern delivery services like DoorDash is instructive: even with gig labor, those companies struggle to be profitable. With full W-2 employment and no delivery fees, we had no chance.`,
    lessonsLearned: `Convenience is not free. Every convenience has a real cost and customers must eventually pay it. Indefinitely subsidizing convenience destroys capital without building sustainable behavior.\n\nThe "no minimums" policy sounded like a consumer benefit. It was a business model flaw. Without minimum order sizes, you attract the worst economics customers.\n\nTest unit economics before scale. A single profitable neighborhood in New York would have told us everything we needed to know about whether this business could ever work.`,
    peakMrr: 1200000,
    teamSize: 1100,
    totalRaised: 280000000,
    aiRootCause: "Cash flow implosion — structurally unprofitable per-delivery economics with no minimum order, no delivery fee, and full W-2 labor costs, making scale worsen rather than improve margins.",
    aiFactors: JSON.stringify(["No delivery fee + no minimum order made every transaction a cash loss", "Full W-2 employee courier staff (not gig) created fixed labor cost unrelated to order volume", "9-city expansion before proving profitability in a single neighborhood", "Pulled IPO at last moment, losing primary capital raising opportunity", "Starbucks partnership brought volume but no improvement in per-order economics"]),
    aiTags: JSON.stringify(["Cash flow", "Execution"]),
    aiVerdict: "Kozmo.com was structurally incapable of profitability from its first order. The combination of no delivery fee, no minimum order size, and full-employment labor model created a negative contribution margin on every transaction that scale made worse, not better.",
  },

  // ── SOCIAL NETWORKS ──────────────────────────────────────────────────────────

  {
    name: "Google+",
    tagline: "Real-life sharing, rethought for the web.",
    industry: "Social Networking",
    foundedYear: 2011,
    closedYear: 2019,
    story: `Google launched Google+ in June 2011 as our answer to Facebook. We had everything: unlimited infrastructure, brand recognition, a built-in user base from Gmail and YouTube, and the engineering talent to build anything.\n\nWe had everything except a reason for people to use it.\n\nIn the first two weeks, 10 million people signed up. The number was misleading — driven by existing Google account holders being invited in. But engagement was hollow. People joined, looked around, found nobody they actually cared about talking to, and left.\n\nThe deeper problem was how we handled growth. Rather than letting Google+ spread organically, we made it mandatory. YouTube comments required a Google+ account. Google search displayed Google+ results prominently. We tried to force integration with every product in the Google portfolio.\n\nUsers resented the coercion. Creators hated the mandatory account linking. Press coverage was uniformly critical. "Ghost town" became the dominant metaphor for the product.\n\nIn 2018 we disclosed a security vulnerability that had exposed 500,000 user accounts. It became the pretext for a shutdown that the engagement numbers had long justified. We closed consumer Google+ in April 2019.`,
    whatFailed: `We launched a social network with no unique reason to exist. Facebook had social graphs that had taken a decade to build. We couldn't reproduce those in weeks with invite campaigns.\n\nThe forced integration strategy — making YouTube comments require a Google+ account — was a product coercion move that generated resentment instead of adoption. You cannot manufacture network effects. They have to be earned through genuine value.\n\nThe "ghost town" problem is existential for social platforms. Once the perception takes hold that nobody is there, it becomes a self-fulfilling prophecy. We could never shake it.`,
    lessonsLearned: `Network effects cannot be manufactured through force. Mandatory integrations with adjacent products create resentment, not adoption.\n\nBeing second in a social network is almost always fatal. Social is a winner-take-most market and Facebook had already won.\n\nProduct-market fit for a social network requires genuine organic behavior, not acquisition metrics. Signups without engagement are a vanity metric.`,
    peakMrr: null,
    teamSize: 1000,
    totalRaised: null,
    aiRootCause: "PMF mismatch — launched a social network with no differentiated value proposition in a market Facebook had already won, then attempted to force adoption through product coercion.",
    aiFactors: JSON.stringify(["No unique value proposition vs Facebook — network effects already belonged to incumbents", "Forced integration with YouTube and other Google products created user resentment", "Ghost town perception became self-fulfilling after initial curiosity period", "Security breach exposing 500k accounts provided regulatory pretext for long-overdue closure", "Signups driven by Google account base misrepresented genuine product adoption"]),
    aiTags: JSON.stringify(["PMF mismatch", "Competition"]),
    aiVerdict: "Google+ failed because access to resources cannot substitute for organic network effects. Google could build the infrastructure of a social network but not the social graph. By the time Google+ launched, Facebook had already accumulated a decade of relationship data that no engineering team could replicate through forced onboarding.",
  },
  {
    name: "Myspace",
    tagline: "A place for friends.",
    industry: "Social Networking",
    foundedYear: 2003,
    closedYear: 2011,
    story: `We were the largest social network in the world. In 2006 Myspace surpassed Google as the most visited website in the United States. News Corp bought us for $580 million in 2005 and told us to grow fast and monetize hard.\n\nWe prioritized advertising revenue over user experience. The site became cluttered with blinking banner ads, auto-playing music profiles, and spam. Profile pages were slow to load. The codebase was a mess of technical debt from years of feature-first development.\n\nFacebook launched at Harvard in 2004 and expanded to all universities by 2005. Where Myspace let users customize everything — background colors, fonts, embedded music — Facebook chose simplicity and standardization. The cleaner, faster Facebook felt like relief after Myspace's visual chaos.\n\nBy 2009 Facebook had surpassed us in unique visitors globally. News Corp sold Myspace in 2011 for $35 million — 6% of what they paid for it.`,
    whatFailed: `We optimized for revenue at the expense of user experience. The parent company imposed ad targets that required increasingly aggressive monetization of the user experience. The result was a cluttered, slow, spam-filled site that drove users to the cleaner alternative that Facebook offered.\n\nThe technical architecture couldn't support the scale we had. As Facebook grew its engineering team and infrastructure, we were fighting legacy code while also trying to add features. We fell behind on mobile, performance, and spam prevention simultaneously.`,
    lessonsLearned: `User experience is not negotiable in social. The moment users have a reason to look elsewhere, they will. Social networks have no switching costs once the social graph migrates.\n\nShort-term ad revenue maximization can destroy long-term platform value. News Corp's revenue targets accelerated user exodus rather than monetizing a growing user base.\n\nMobile was the platform shift. We missed it entirely while Facebook shipped a mobile app that worked.`,
    peakMrr: null,
    teamSize: 1600,
    totalRaised: 580000000,
    aiRootCause: "Competition and execution failure — ad-revenue optimization degraded user experience while Facebook offered a cleaner, faster alternative, causing rapid social graph migration.",
    aiFactors: JSON.stringify(["Aggressive monetization via ad clutter degraded user experience critically", "Technical debt made platform slow and spam-ridden relative to Facebook", "Failed to adapt to mobile platform shift while Facebook shipped mobile-first features", "News Corp acquisition created revenue targets incompatible with user experience investment", "Social graph migration is irreversible — once users left, the network effect inverted"]),
    aiTags: JSON.stringify(["Competition", "Execution"]),
    aiVerdict: "Myspace's collapse is a case study in the conflict between short-term revenue and long-term platform health. The decision to prioritize ad monetization over user experience handed Facebook the exact differentiator they needed. Once social graphs begin migrating, the process is self-reinforcing and irreversible.",
  },
  {
    name: "Clubhouse",
    tagline: "Drop-in audio chat. Be here now.",
    industry: "Social Audio",
    foundedYear: 2020,
    closedYear: 2023,
    story: `We launched in March 2020, twelve days after the WHO declared a COVID-19 pandemic. The timing was a miracle and a curse.\n\nPeople were locked in their homes, desperate for human connection and intellectual stimulation. Clubhouse offered something genuinely new: live, unscripted audio conversations between fascinating people. You could drop into a room where Marc Andreessen and Elon Musk were debating the future of technology. Where hip-hop producers were workshopping beats. Where strangers were processing grief together.\n\nWe were invite-only and iOS-only. We were valued at $4 billion before most people had heard of us.\n\nThen the world opened back up. And Twitter launched Spaces. And Facebook launched Live Audio Rooms. And Spotify launched Greenroom. Every major platform cloned our exact feature set in months.\n\nOur MAU peaked at 9.6 million in February 2021, one year in. By December 2021 it had fallen below 1 million. The thing we'd built was a pandemic artifact — real and valuable in a specific context, gone when that context ended.\n\nWe laid off more than half our staff in April 2023.`,
    whatFailed: `Our product was intrinsically tied to lockdown behavior. Long-form live audio requires uninterrupted attention — something people had in abundance when they were home all day and nothing to do.\n\nWhen the world returned to offices, gyms, and restaurants, the 90-minute audio conversation with strangers stopped fitting into daily life. The format didn't translate to the post-pandemic context.\n\nThe cloning by Twitter, Facebook, and Spotify was faster than we could build defensibility. Our only moat was the social graph of interesting early users. When Twitter had the same features with 300 million existing users, our moat disappeared.`,
    lessonsLearned: `Pandemic conditions are not market conditions. Behaviors that emerge under extreme social restriction may not survive the return to normalcy.\n\nExclusivity (invite-only, iOS-only) can create hype but it also creates a window for competitors to study your product and ship clones before you reach defensible scale.\n\nLong-form audio is a niche format. Niche formats can generate enormous hype but rarely become mass market behaviors.`,
    peakMrr: null,
    teamSize: 150,
    totalRaised: 310000000,
    aiRootCause: "Market timing and competition — growth driven by pandemic-specific behavior that evaporated when lockdowns ended, followed by rapid cloning by incumbent platforms.",
    aiFactors: JSON.stringify(["Core use-case (long-form live audio) required lockdown conditions that ended in 2021", "Twitter Spaces, Facebook Live Audio, Spotify Greenroom cloned product within months", "Invite-only and iOS-only exclusivity created a public demo period for competitors to study", "MAU collapsed 90% within 12 months of peak as pandemic behavior normalized", "No durable format defensibility — audio rooms could be replicated in weeks by any large platform"]),
    aiTags: JSON.stringify(["Market timing", "Competition"]),
    aiVerdict: "Clubhouse is a pandemic artifact that was mistaken for a category. The product filled a genuine human need in a specific historical context and then ceased to fill it when that context ended. The rapid incumbent cloning eliminated any window for the company to find durable product-market fit.",
  },

  // ── ENTERPRISE / B2B ────────────────────────────────────────────────────────

  {
    name: "WeWork",
    tagline: "Do what you love. We'll handle the space.",
    industry: "Proptech / Coworking",
    foundedYear: 2010,
    closedYear: 2023,
    story: `We were going to change the way the world worked. Not just offices — consciousness. Adam believed this, and for a while, so did everyone around him.\n\nAt our core, we were a real estate arbitrage business: we signed long-term leases on commercial space and sublet it on short-term flexible terms to companies and individuals. The margins on that trade required occupancy rates above 80% to be sustainable. We rarely maintained those rates consistently.\n\nSoftBank invested $10.65 billion. Our valuation peaked at $47 billion. We were the most valuable startup in America.\n\nThen we filed for an IPO in 2019 and the S-1 disclosed everything: $1.9 billion in losses on $1.8 billion in revenue. Adam Neumann had sold shares, borrowed against his stake, trademarked "We" and sold the trademark back to the company for $5.9 million. The board had given him supervoting shares that made him effectively unremovable.\n\nThe IPO was withdrawn. Adam was ousted. SoftBank wrote down billions. We filed for bankruptcy in November 2023.`,
    whatFailed: `The business model was structurally dangerous: long-term lease obligations on the liability side, short-term membership revenue on the asset side. In any economic downturn — or pandemic — that mismatch is fatal. Members can cancel in 30 days. Landlords cannot.\n\nWe were valued as a tech company but were a real estate company. Tech multiples on real estate economics require technology that transforms the economics. We never built that. The tech was a UI on top of a lease arbitrage trade.\n\nCorporate governance was catastrophic. One person controlled the company with no checks. The conflicts of interest were not edge cases — they were structural.`,
    lessonsLearned: `Real estate is not software. If you're signing leases, you are in the real estate business, regardless of your app. Price accordingly.\n\nVCs can enable governance failures by prioritizing growth over accountability. The board allowed Adam's behavior because the valuation was going up.\n\nA charismatic founder narrative does not substitute for a viable business model. At some point, every company has to show that it makes money.`,
    peakMrr: 200000000,
    teamSize: 14000,
    totalRaised: 22000000000,
    aiRootCause: "Execution and cash flow failure — real estate arbitrage business misrepresented as tech company, with fatal maturity mismatch between long-term lease liabilities and short-term membership revenue.",
    aiFactors: JSON.stringify(["Long-term lease liabilities vs short-term membership contracts created structural insolvency risk", "Misrepresentation as 'tech company' to justify $47B valuation without tech-level economics", "CEO had unchecked power through supervoting shares, enabling conflicts of interest", "COVID-19 triggered simultaneous mass cancellations while lease obligations remained fixed", "SoftBank's Vision Fund created perverse incentives — burning cash was rewarded with more capital"]),
    aiTags: JSON.stringify(["Cash flow", "Execution"]),
    aiVerdict: "WeWork is a case study in what happens when narrative replaces analysis. The company's real estate arbitrage model had structural fragility baked in from day one — and governance failures prevented any accountability mechanism from correcting course before the exposure was catastrophic.",
  },

  // ── ON-DEMAND / GIGS ────────────────────────────────────────────────────────

  {
    name: "Homejoy",
    tagline: "Professional home cleaning, on demand. Book in 60 seconds.",
    industry: "On-Demand Services",
    foundedYear: 2010,
    closedYear: 2015,
    story: `We were the "Uber for home cleaning." We raised $38 million from Google Ventures, PayPal co-founder Max Levchin, and top-tier VCs. We were in 30 cities. We were growing.\n\nOur model: customers book a cleaning through our platform, we dispatch independent contractors, we take 25%. The cleaner earns $12-15/hour. The customer pays $25/hour for the clean. Simple.\n\nThe problem was multi-layered. To acquire customers, we'd heavily discount the first cleaning — sometimes offering $19 cleanings to a market where the actual cost was $35. Customers loved the deal. They converted. And then 20-30% of them bypassed the platform entirely and hired the cleaners directly.\n\nWe were training customers and cleaners to cut us out. The churn was brutal. The customer acquisition costs were astronomical. And in July 2015, four cleaning contractors filed lawsuits arguing they were employees, not contractors. The legal exposure made the entire business model unviable to continue. We shut down that month.`,
    whatFailed: `The discount-first acquisition strategy trained customers to see us as a coupon, not a platform. Once they'd used us once at a discounted rate, the off-platform relationship with the cleaner was obviously better for everyone except us.\n\nThe worker classification issue was existential and we knew it was coming. The entire on-demand cleaning sector had this problem, and we didn't have the legal or financial resources to fight it at the same time as running the business.`,
    lessonsLearned: `Never use heavy discounts to acquire customers if your value proposition doesn't justify the full price. A customer who came for the deal will leave when the deal ends.\n\nThe gig economy model depends on the legal classification of workers as contractors. If that classification is vulnerable, the entire business model is vulnerable. Understand your legal exposure before scaling.\n\nPlatforms that facilitate two-sided markets must create network value that exceeds what either side could capture bilaterally. We didn't.`,
    peakMrr: 2000000,
    teamSize: 100,
    totalRaised: 38000000,
    aiRootCause: "Cash flow and Execution failure — heavy acquisition discounts trained users to bypass the platform, while worker reclassification lawsuits eliminated the contractor-based business model.",
    aiFactors: JSON.stringify(["Heavy first-booking discounts trained customers to bypass platform for direct cleaner relationships", "20-30% of customers converting to off-platform bookings destroyed long-term unit economics", "Worker misclassification lawsuits created legal liability that made the model unviable", "High churn rate required constant customer acquisition spending with poor payback periods", "30-city expansion before proving retention metrics in any single market"]),
    aiTags: JSON.stringify(["Cash flow", "Execution", "Regulatory"]),
    aiVerdict: "Homejoy's failure was dual-track: the discount acquisition strategy systematically undermined the platform by teaching both sides to operate without it, while the contractor classification legal threat eliminated the economics that made the model possible at all.",
  },
  {
    name: "Munchery",
    tagline: "Chef-crafted meals, delivered to your door.",
    industry: "Food Delivery / Ghost Kitchen",
    foundedYear: 2010,
    closedYear: 2019,
    story: `We wanted to solve the problem of weeknight dinner. Not with restaurant delivery — with chef-prepared, ready-to-heat meals made fresh daily and delivered to your door.\n\nThe idea was beautiful: hire professional chefs, source quality ingredients, prepare meals in central kitchens, and deliver them in a three-hour window every evening. The customer gets a restaurant-quality dinner for $10-13. The chef gets to cook without working a brutal restaurant service.\n\nWe raised $125 million. We expanded from San Francisco to Seattle, LA, and New York. We were generating significant revenue.\n\nThe operations were a nightmare. Fresh food has a shelf life measured in hours. Meals that weren't ordered were wasted. Meals that were ordered late in the day were sometimes unavailable. The coordination of chef scheduling, ingredient sourcing, prep timing, and delivery routing was a logistics challenge that absorbed money faster than revenue could replace it.\n\nUber Eats and DoorDash entered the market in 2014-2015. They could offer restaurant delivery — a vastly larger selection — with no kitchen costs. We were competing against a model with structurally lower capital requirements.\n\nWe filed for bankruptcy in January 2019, having spent most of our $125 million.`,
    whatFailed: `We chose to be both a food manufacturer and a delivery company — two hard problems combined into one harder problem. Each part of the operation required different expertise, different capital, and different optimization.\n\nThe food waste problem was endemic and unfixable. Fresh meals prepared daily to projected demand will always have waste. We could never balance the twin failures of ordering out and running out.\n\nRestaurant delivery platforms eliminated the need for a vertically integrated meal company. Customers got more selection for similar prices from Uber Eats. Our differentiation — chef quality, freshness — wasn't enough to justify a smaller menu.`,
    lessonsLearned: `Vertical integration sounds like competitive moat. Often it's just more operational complexity without proportionally more value delivered to customers.\n\nFood waste is a structural cost in any fresh-food business. If the business model can't absorb that cost, the model is wrong.\n\nNever compete with asset-light platforms by being asset-heavy. If the alternative needs no kitchen, your kitchen is a liability.`,
    peakMrr: 3000000,
    teamSize: 250,
    totalRaised: 125000000,
    aiRootCause: "Cash flow collapse through operational complexity — combined food manufacturing and delivery into one capital-intensive operation that couldn't compete with asset-light restaurant delivery platforms.",
    aiFactors: JSON.stringify(["Structural food waste from daily fresh prep against projected demand was unfixable", "Asset-heavy ghost kitchen model couldn't compete with asset-light delivery aggregators", "Expanded to 4 cities before proving profitability in San Francisco", "Uber Eats and DoorDash offered more selection at similar prices without production costs", "Vertical integration created operational complexity that absorbed capital without proportional margin improvement"]),
    aiTags: JSON.stringify(["Cash flow", "Competition"]),
    aiVerdict: "Munchery tried to solve a logistics problem by becoming a food manufacturer, then found itself competing with platforms that had no production costs. The ghost kitchen model requires operational perfection at scale — a standard the company never reached before running out of capital.",
  },

  // ── FINTECH / CRYPTO ────────────────────────────────────────────────────────

  {
    name: "Fab.com",
    tagline: "Inspiring design for every budget. Flash sales on beautiful things.",
    industry: "Design E-commerce",
    foundedYear: 2010,
    closedYear: 2015,
    story: `We were a billion-dollar company. Our valuation reached $1 billion in 2012. We were growing 30% month-over-month. We had 10 million users. Design Twitter loved us. Architecture blogs featured our products. We had achieved something genuinely hard: curation at scale.\n\nAnd then Jason Goldberg, our CEO, decided to bet everything on international expansion and a pivot from flash sales to full-price retail.\n\nWe spent $60-100 million trying to crack Europe. We hired hundreds of employees in Germany, the UK, and the Netherlands. We rented offices. We built local operations. None of it worked. European consumers had different design aesthetics, different e-commerce habits, and different price tolerance than we'd assumed.\n\nSimultaneously, we abandoned the flash sale model that had made us special. Flash sales created urgency and curation — two things that drive conversion. Full-price, always-on retail was what every other design e-commerce site did. We became generic.\n\nWe laid off 440 employees in 2013. Then another 100. By 2015 we had sold the company for a fraction of our peak valuation. We burned $200 million of the $330 million we'd raised.`,
    whatFailed: `We had found product-market fit with flash sales and walked away from it. The flash sale model had energy, urgency, and curation. The pivot to always-on retail had none of those things. We voluntarily destroyed our differentiation.\n\nThe European expansion was a capital misallocation of historic proportions. We had no evidence the European market wanted what we offered and we bet $60-100 million finding out it didn't.\n\nGrowth metrics masked unit economics problems. We were measuring GMV and user growth while margin per order was declining as we scaled.`,
    lessonsLearned: `When you've found product-market fit, changing the model is an enormous risk that requires very strong evidence. We changed our model based on the CEO's vision, not market signals.\n\nInternational expansion requires deep local market research before capital deployment. What works in New York doesn't automatically work in Munich.\n\nGMV is not a business metric. Revenue minus costs is a business metric. We confused the two until we ran out of money.`,
    peakMrr: 15000000,
    teamSize: 700,
    totalRaised: 330000000,
    aiRootCause: "Pivot failure and cash flow — voluntarily abandoned a working flash-sale model to pursue generic full-price retail while simultaneously burning $60-100M on a failed European expansion.",
    aiFactors: JSON.stringify(["Abandoned flash-sale model that had genuine PMF for generic always-on retail", "Spent $60-100M on European expansion without validating market fit", "GMV and user growth metrics masked declining per-order margins", "440-person layoff destroyed team morale and execution capacity", "CEO drove strategy changes based on vision rather than market evidence"]),
    aiTags: JSON.stringify(["Pivot failure", "Cash flow", "Execution"]),
    aiVerdict: "Fab.com voluntarily destroyed its own competitive advantage. The flash sale model had genuine differentiation — curation, urgency, discovery. By pivoting to commodity retail and burning capital on an unvalidated European market, the company eliminated its moat and its runway simultaneously.",
  },

  // ── HARDWARE ────────────────────────────────────────────────────────────────

  {
    name: "Segway",
    tagline: "Personal transportation. Reimagined.",
    industry: "Personal Mobility / Hardware",
    foundedYear: 1999,
    closedYear: 2020,
    story: `Dean Kamen invented us in secret. Steve Jobs told a journalist we would be "bigger than the Internet." John Doerr, the greatest VC of his era, compared the launch to the creation of the Internet. Jeff Bezos invested.\n\nWe launched in 2001. The prediction was 10,000 units per week. We sold 6,000 in our first year.\n\nThe Segway was a genuine technological achievement — a self-balancing personal mobility device using gyroscopes and sophisticated software. It was also $5,000, weighed 83 pounds, had a top speed of 12 mph, required charging every 12 miles, and was banned from most sidewalks within years of launch.\n\nWe found a market: mall security guards, warehouse workers, tourist operators, and police departments. It was a niche market, not the revolution we'd promised.\n\nKamen sold the company in 2009. By 2020 the new owner, Ninebot, announced the Segway personal transporter product line would be discontinued. The category had been disrupted by electric scooters and e-bikes that were cheaper, lighter, and more practical.`,
    whatFailed: `The hype created expectations that were structurally impossible to meet. Kamen had promised to solve urban transportation. The Segway required you to already be able to walk, cost more than a used car, and was illegal in most places you'd want to use it.\n\nThe use case was undefined. We didn't know who our customer was because we believed everyone would be our customer. When "everyone" is your market, you have no market.\n\nE-bikes and electric scooters eventually did what we promised to do, at 10% of our price and 10% of our weight. We were the proof of concept for a category we couldn't capture.`,
    lessonsLearned: `Extraordinary hype creates extraordinary expectations. Never let media and investor excitement outpace what you've actually validated.\n\nBeing first to a category does not mean you win the category. First-mover advantage requires defensibility. We had patents, not defensibility.\n\nIdentify your specific customer before launch. "Everyone who walks" is not a customer segment.`,
    peakMrr: 500000,
    teamSize: 400,
    totalRaised: 170000000,
    aiRootCause: "PMF mismatch — promised a transportation revolution but delivered a $5,000 niche vehicle banned on most sidewalks, while cheaper, lighter electric mobility alternatives eventually captured the category.",
    aiFactors: JSON.stringify(["Massive pre-launch hype created expectations ($10,000 units/week) impossible to meet", "No defined customer segment — 'everyone who walks' is not a market", "$5,000 price point with 83-lb weight limited accessible use cases fundamentally", "Sidewalk bans in most cities eliminated the primary intended use case", "E-bikes and electric scooters delivered the promise at 10% of the cost"]),
    aiTags: JSON.stringify(["PMF mismatch", "Market timing"]),
    aiVerdict: "Segway invented a category and then failed to own it. The technology was real but the product economics, weight, legal context, and price prevented it from ever reaching the mass market Kamen envisioned. Electric scooters eventually fulfilled the Segway promise by solving every constraint Segway couldn't.",
  },

  // ── MEDIA / CONTENT ─────────────────────────────────────────────────────────

  {
    name: "Napster",
    tagline: "Share and discover music. Free, from any computer.",
    industry: "Music / P2P Technology",
    foundedYear: 1999,
    closedYear: 2002,
    story: `Shawn Fanning built Napster in his dorm room. I helped him launch it. Within 18 months we had 80 million registered users. We were the fastest-growing software in history at the time.\n\nWe also had no license from any record label, no revenue model, and were facilitating the free distribution of hundreds of millions of copyrighted files.\n\nThe Recording Industry Association of America sued us in December 1999, five months after launch. The lawsuit was not a surprise — we knew what we were building. Metallica sued us in April 2000 after discovering their unreleased music on our platform. Dr. Dre sued the same month.\n\nWe tried to negotiate with the labels. We tried to propose a subscription model where labels would receive revenue from a blanket license. Bertelsmann AG invested $85 million and tried to help us go legitimate. But the legal walls closed too fast.\n\nA federal judge ordered us to prevent the sharing of copyrighted music in February 2001. We couldn't do it perfectly — P2P networks aren't designed for content filtering. By July 2001 we shut down to comply with the injunction. We filed for bankruptcy in June 2002.\n\nSpotify built a legal version of what we were and launched 6 years later. They reached a $67 billion valuation. We were the proof of concept.`,
    whatFailed: `We built something people genuinely wanted — free, instant access to any music ever recorded — without a business model or legal foundation. The demand was validated on day one. The legality was violated on day one.\n\nThe failure wasn't technological or market-related. The failure was building a product that required the cooperation of an industry that had every incentive to destroy you.`,
    lessonsLearned: `Demand validation is not the same as business validation. 80 million users who pay nothing and expose you to unlimited legal liability is not a business.\n\nDisrupting incumbent industries with technology that makes their existing business model obsolete will cause them to defend it with every legal tool available.\n\nThe monetization conversation cannot come after the copyright question. If you need content licenses to operate legally, get the licenses before you launch.`,
    peakMrr: null,
    teamSize: 70,
    totalRaised: 85000000,
    aiRootCause: "Regulatory failure — built a product that required music industry cooperation but didn't obtain it, creating infinite legal liability that court injunctions eventually forced into shutdown.",
    aiFactors: JSON.stringify(["Launched without content licenses from any record label — structural legal exposure from day one", "RIAA, Metallica, and Dr. Dre lawsuits created legal costs and injunctions that couldn't be survived", "Bertelsmann investment for legitimate pivot came too late — injunctions arrived before deal could complete", "P2P architecture made court-ordered content filtering technically impossible to perfect", "Revenue model was nonexistent — 80M users with $0 revenue and unlimited legal liability"]),
    aiTags: JSON.stringify(["Regulatory", "Execution"]),
    aiVerdict: "Napster proved the product concept for legal music streaming, then handed the opportunity to Spotify. The failure was not about demand — 80 million users proved the demand. The failure was launching a product that required industry cooperation without obtaining it, creating a legal exposure that no funding round could overcome.",
  },

  // ── MISC / UNIQUE FAILURES ──────────────────────────────────────────────────

  {
    name: "Color Labs",
    tagline: "Share moments with the people physically around you.",
    industry: "Mobile Social / Photo",
    foundedYear: 2011,
    closedYear: 2012,
    story: `We raised $41 million before launching a single product. Not a prototype. Not a beta. Before anything. The round was led by Sequoia and Bain Capital, and it was announced publicly before the app was live.\n\nThe announcement created the kind of pressure that destroys products. Journalists tried our app before there were enough users to make it work — the product was a proximity-based photo sharing app that required many nearby users to be interesting. In downtown San Francisco, at 9am, nobody was using Color.\n\nThe reviews were brutal. The TechCrunch headline called the product "deeply problematic." The Verge wondered if we'd "lost the plot." Users downloaded the app, found nobody nearby, and deleted it.\n\nThe core concept required a critical mass of simultaneous nearby users that we could never achieve through organic growth. A social app that only works when many people are present, in the same place, at the same time — is a bootstrap problem with no solution.\n\nWe pivoted twice. We tried enterprise social. We tried a different consumer product. Nothing worked.\n\nApple acquired our engineering team in October 2012 for approximately $7 million — 17% of what we'd raised.`,
    whatFailed: `The product suffered from a cold-start problem that was structurally irresolvable. Proximity-based social requires density. Density requires existing users. Existing users require a working product. The circle could not be squared.\n\nThe $41 million pre-launch announcement created massive scrutiny before we had anything to show. Early reviewers experienced a product designed for crowds — alone. The impression formed in those early reviews never recovered.`,
    lessonsLearned: `Never announce a round and a product simultaneously if the product requires a network effect to be experienced correctly. The first impression cannot be taken back.\n\nNetwork effects must be engineered at launch, not assumed to emerge. If the product doesn't work for user #1, no amount of capital solves it.\n\nPre-announce funding only creates pressure. It accelerates scrutiny without accelerating product quality.`,
    peakMrr: null,
    teamSize: 70,
    totalRaised: 41000000,
    aiRootCause: "PMF mismatch — proximity-based social product required simultaneous high user density that was never achievable, combined with catastrophic first-impression damage from pre-launch media scrutiny.",
    aiFactors: JSON.stringify(["Cold-start network problem was irresolvable — product required density it couldn't bootstrap", "Pre-launch announcement of $41M funding created media scrutiny before product was testable", "Early reviewers experienced proximity product in isolation — no nearby users — forming permanent negative impression", "Two pivots failed to find new direction — team eventually acqui-hired for talent not product", "Chicken-and-egg density problem had no engineerable solution at their go-to-market approach"]),
    aiTags: JSON.stringify(["PMF mismatch", "Execution"]),
    aiVerdict: "Color Labs is the canonical case of pre-launch hype destroying a product that was never viable. The $41M announcement forced premature scrutiny on a product that required network density to function. The first impression was formed by people who were fundamentally alone in a product designed for crowds.",
  },
  {
    name: "Secret",
    tagline: "Share things anonymously with your friends and the world.",
    industry: "Anonymous Social",
    foundedYear: 2013,
    closedYear: 2015,
    story: `We launched in January 2014. By March we were a top app in the App Store. By June we had raised $35 million at a $100 million valuation. Anonymous confessions from Silicon Valley insiders went viral. Secrets about startup layoffs, founder breakdowns, and VC drama spread across Twitter and press coverage.\n\nThen the product became what anonymous products always become: a harassment machine.\n\nTargeted anonymous attacks on individuals — founders, employees, students — became the dominant content type. Bullying, outing of private information, and false rumors drove users away while attracting media coverage about harm. The Brazilian regulators banned us.\n\nWe shipped features to reduce harm: phone number verification, friend-of-friend posting restrictions, report buttons. None of it was sufficient. The core feature — anonymity without accountability — made the harm structural, not incidental.\n\nIn April 2015, 16 months after launch, David (my co-founder) and I returned the remaining capital — approximately $6 million — to investors and shut the company down. It was the right thing to do.`,
    whatFailed: `Anonymous social media has one failure mode: the mean-spirited and harmful behavior scales faster than the thoughtful and valuable behavior. We had no mechanism to select for good actors.\n\nSilicon Valley confessions made for great press in the early weeks. They were a small fraction of total posts. The bulk of the content was what anonymous content always becomes when accountability is removed.`,
    lessonsLearned: `Returning capital when you cannot fix a product's fundamental harm is the right call. We did it. It was one of the best decisions we made.\n\nAnonymity and accountability are in tension. Every anonymous platform must make a structural choice about how to manage that tension. Bolted-on moderation cannot fix an architectural anonymity problem.\n\nPress coverage of early viral content is not a signal of product-market fit. It's a signal of novelty.`,
    peakMrr: null,
    teamSize: 15,
    totalRaised: 35000000,
    aiRootCause: "PMF mismatch and Regulatory — anonymous platform designed without accountability mechanisms allowed harassment to become the dominant use case, leading to founder-driven shutdown and return of remaining capital.",
    aiFactors: JSON.stringify(["No accountability mechanism made harassment structurally inevitable and unfixable", "Early viral content (Silicon Valley confessions) was novelty, not PMF signal", "Brazilian regulatory ban previewed the legal exposure that would have grown globally", "Moderation bolted on after launch cannot fix architectural anonymity flaws", "Co-founders recognized product was causing net harm and voluntarily shut down"]),
    aiTags: JSON.stringify(["PMF mismatch", "Regulatory"]),
    aiVerdict: "Secret's founders made an unusual choice: they returned the remaining capital and shut down rather than continuing to operate a product they recognized was causing net harm. The anonymity-without-accountability architecture made harassment structurally inevitable. The shutdown was an act of integrity.",
  },
  {
    name: "Pebble",
    tagline: "The smartwatch for everyone. Kickstarted by you.",
    industry: "Wearables / Smartwatch",
    foundedYear: 2012,
    closedYear: 2016,
    story: `We raised $10.3 million on Kickstarter in 2012 — the largest Kickstarter campaign in history at the time. We validated that people wanted a smartwatch before Apple knew smartwatches were a product. We shipped 2 million units. We had the best e-ink display, the longest battery life, and the most passionate user community in wearables.\n\nApple Watch launched April 2015. It was expensive ($349+), had a one-day battery life, and required an iPhone. Our watch cost $99, lasted a week on a charge, and worked with iPhone and Android.\n\nThe Apple Watch still destroyed us.\n\nApple's marketing halo made smartwatch synonymous with Apple Watch in mainstream consumer perception. The press covered Apple Watch endlessly. Retail shelf space consolidated around Apple. Developers built for WatchOS, not Pebble.\n\nWe raised $26 million in a second Kickstarter in 2015 — still the biggest wearables crowdfund ever. By late 2016 we were out of money. Fitbit acquired us for $23 million — our user data and some IP. The product was discontinued. Our community of 2 million users lost access to their watches within months.`,
    whatFailed: `We couldn't compete with Apple's distribution, developer ecosystem, and brand. In consumer hardware, being technically better doesn't win. Being distributed better wins.\n\nThe crowdfunding model gave us validation and capital but no path to retail distribution or a recurring revenue model. We were episodic in our funding — big Kickstarter campaigns every 18 months — rather than building a sustainable business between campaigns.`,
    lessonsLearned: `First-mover advantage in hardware categories is fragile if your category gets validated and then captured by a platform player with infinite distribution.\n\nCrowdfunding can build community and validate products but it is not a business model. You still need a sustainable revenue and distribution strategy.\n\nTechnical superiority (battery life, compatibility) does not guarantee market capture when competing with a product backed by ecosystem lock-in.`,
    peakMrr: 4000000,
    teamSize: 160,
    totalRaised: 36000000,
    aiRootCause: "Competition — validated the smartwatch category, then had the category captured by Apple's ecosystem lock-in, developer ecosystem, and retail distribution before Pebble could build sustainable competitive moats.",
    aiFactors: JSON.stringify(["Apple Watch captured mainstream consumer smartwatch perception despite inferior battery and price", "Crowdfunding provided capital but no path to sustainable retail distribution or recurring revenue", "Developer ecosystem consolidated around WatchOS, leaving Pebble with declining app quality", "Acquisition for $23M returned almost nothing to investors despite 2M unit sales and passionate community", "No recurring revenue model between Kickstarter campaigns made financials episodic and fragile"]),
    aiTags: JSON.stringify(["Competition", "Cash flow"]),
    aiVerdict: "Pebble built the right product before the market existed and was unable to defend the category once Apple decided to enter it. In consumer electronics, technical merit yields to ecosystem power. Pebble validated the smartwatch category and Apple captured it.",
  },
  {
    name: "Mixer",
    tagline: "A new era of interactive live streaming.",
    industry: "Live Streaming / Gaming",
    foundedYear: 2016,
    closedYear: 2020,
    story: `Microsoft acquired us — then called Beam — in August 2016 for $70 million. We had built a live streaming platform with a genuinely differentiated technical feature: sub-second latency. Twitch had 7-15 second delays. We had under one second. The interactive possibilities were real.\n\nMicrosoft believed we could take on Twitch by signing exclusive streaming deals with top creators. In 2019, we signed Ninja — the most popular Twitch streamer in the world — to an exclusive deal reportedly worth $20-30 million. Then Shroud. Then King Gothalion. Then Ewok.\n\nThe talent deals cost hundreds of millions. The audience didn't follow.\n\nNinja had built his audience on Twitch. His fans watched him on Twitch. When he moved to Mixer, a significant portion of his audience didn't move with him. The platform still had no one else to watch. Creator-first strategies only work if the creator brings their audience — and audiences are surprisingly platform-loyal.\n\nIn June 2020, two months after COVID-19 locked the world indoors and sent Twitch viewership to record highs, Microsoft shut Mixer down. We hadn't grown despite massive investment. Our competitors had grown without effort.`,
    whatFailed: `Talent acquisition is not audience acquisition. We assumed Ninja's 14 million Twitch followers would migrate to Mixer. Many didn't. The audience had platform habits, friend groups, and discovery mechanisms embedded in Twitch that a streaming contract couldn't transplant.\n\nWe invested billions in creator exclusives without building the platform features, discovery algorithms, or community tools that would make Mixer a destination independent of any individual creator. One departure, one contract ending — and the whole strategy collapsed.`,
    lessonsLearned: `In live streaming, the network effect is the product. Viewers follow other viewers. Content is a catalyst, not a platform.\n\nTalent deals buy attention, not loyalty. Sustainable platforms need features and communities that persist beyond any individual creator.\n\nClosed at exactly the moment the market exploded. COVID turned live streaming into mass media. The window to capture that growth was lost because we shut down the month it opened.`,
    peakMrr: null,
    teamSize: 300,
    totalRaised: 400000000,
    aiRootCause: "Competition and Execution failure — talent acquisition strategy assumed creator audiences were portable, but Twitch's network effects retained viewership despite exclusive deals costing hundreds of millions.",
    aiFactors: JSON.stringify(["Creator audience portability assumption was wrong — Twitch network effects retained viewers despite Ninja exclusivity", "Hundreds of millions spent on talent deals with no corresponding audience or platform growth", "No discovery, community, or algorithmic features built to make Mixer independently compelling", "Closed in June 2020 — exactly when COVID-driven streaming growth hit record Twitch viewership", "Platform loyalty and social graph are the real product of live streaming — not any single creator"]),
    aiTags: JSON.stringify(["Competition", "Execution"]),
    aiVerdict: "Mixer collapsed because talent acquisition and audience acquisition are different things. Microsoft spent hundreds of millions on streaming exclusives while Twitch retained the social graphs, habits, and discovery systems that keep viewers on a platform. Shutting down in June 2020 — the peak of pandemic streaming — was the final irony.",
  },
  {
    name: "Ello",
    tagline: "A beautiful, ad-free social network. For humans.",
    industry: "Social Networking",
    foundedYear: 2014,
    closedYear: 2020,
    story: `We launched in August 2014, directly into a Facebook privacy controversy. Our manifesto was simple: we will never sell ads. We will never sell your data. You are a person, not a product.\n\nIn the first 72 hours, we received 50,000 sign-up requests per hour. We had to queue registrations. The viral spread was driven entirely by the anti-Facebook sentiment that had been building for years.\n\nBut we had no revenue model. The ad-free, data-free promise that made us viral also meant we had no business model beyond a freemium plan where users paid for premium features. Very few paid.\n\nThe privacy wave crested and retreated. Facebook didn't die. The outrage cycle moved on. Our user growth slowed, then reversed. The passionate early adopters who'd signed the manifesto alongside us began drifting back to where their social graphs lived.\n\nBy 2016 we'd pivoted to focus on the creative community — artists, designers, illustrators — as a portfolio and discovery platform. We raised $5.5 million but remained subscale. In 2020 the new ownership attempted to relaunch without success. The platform operates at minimal scale today.`,
    whatFailed: `We built a business on an ideological promise without a revenue model. Being ad-free is not a business model — it's a feature. The users who came for the anti-Facebook moment weren't willing to pay for the alternative.\n\nPrivacy waves are cyclical. The anger passes. The social graph doesn't move. Users return to the platform where their relationships exist, regardless of privacy concerns.`,
    lessonsLearned: `Ideological positioning can drive viral acquisition but it rarely sustains retention. The users who come because they hate Facebook leave when the outrage subsides.\n\nFreemium requires the free tier to be genuinely valuable and the paid tier to be genuinely compelling. We had both, but the payment conversion rate was too low to sustain the company.\n\nSocial networks require a migration event for the social graph to move. Individual user acquisition doesn't work — the whole friend group has to move together.`,
    peakMrr: 200000,
    teamSize: 25,
    totalRaised: 5500000,
    aiRootCause: "PMF mismatch — built on anti-Facebook sentiment without a sustainable revenue model, with user growth peaking at a viral moment that didn't translate to a durable business.",
    aiFactors: JSON.stringify(["No revenue model — 'no ads, no data selling' promise eliminated primary social network monetization paths", "Viral acquisition driven by outrage cycle rather than durable product value", "Freemium conversion rate too low to sustain operations at meaningful scale", "Social graph lock-in kept users on Facebook even when they philosophically preferred Ello", "Pivot to creative professional community came too late and with insufficient capital"]),
    aiTags: JSON.stringify(["PMF mismatch", "Cash flow"]),
    aiVerdict: "Ello captured a genuine anti-Facebook sentiment but failed to convert ideological alignment into a sustainable business. The no-ads promise was the product differentiator and the business model killer simultaneously. When the privacy outrage cycle ended, the social graph didn't follow.",
  },
  {
    name: "Shyp",
    tagline: "Shipping made simple. Pick up and package anything, on demand.",
    industry: "On-Demand Logistics",
    foundedYear: 2013,
    closedYear: 2018,
    story: `We built Shyp to solve the worst part of selling things online: getting them to the buyer. Take a photo of your item, request a pickup, and we'd send someone to collect, package, and ship it for you. No boxes. No tape. No post office.\n\nWe raised $62 million. Andreessen Horowitz led our Series B. We were expanding to New York, Chicago, Los Angeles, Miami. Growth metrics were impressive.\n\nWe were also losing money on nearly every transaction. The cost of sending a courier to pick up an item, professionally packaging it, and handing it off to USPS/FedEx/UPS was often higher than what we charged. We charged a flat $5 pickup fee for the courier visit regardless of how small the package was.\n\nIn 2016 our CEO wrote a candid public letter acknowledging we'd grown too fast, into too many cities, before our unit economics were healthy. We pulled back to San Francisco only. We raised prices. We stopped the consumer market and pivoted to business customers.\n\nNone of it was enough. We announced the shutdown in March 2018.`,
    whatFailed: `We confused growth metrics with business health. Our expansion to multiple cities looked like success. Each new city was a new set of fixed costs on top of already-negative unit economics. Scale didn't fix the unit economics — it amplified them.\n\nThe $5 flat pickup fee was designed to drive conversion. It did. But a courier pickup, regardless of shipment value, costs $10-20 in labor. We were structurally losing money on every pickup from day one.`,
    lessonsLearned: `Unit economics are not a metric to track — they are the metric. Everything else is noise until they're healthy.\n\nThe founders who publicly acknowledge mistakes before the company dies give themselves and their teams the best chance. Our CEO's 2016 letter was honest and early. It didn't save us but it was the right thing.\n\nExpanding markets before proving unit economics in a single market is a reliable way to scale losses.`,
    peakMrr: 1000000,
    teamSize: 100,
    totalRaised: 62000000,
    aiRootCause: "Cash flow from inverted unit economics — $5 flat pickup fee charged while paying $10-20 in labor per courier visit, with multi-city expansion amplifying losses before the core model was profitable.",
    aiFactors: JSON.stringify(["$5 pickup fee vs $10-20 labor cost per courier visit made every transaction a cash loss", "Expanded to NYC, Chicago, LA, Miami before San Francisco was unit-economics positive", "Growth metrics (pickup volume, city count) obscured per-transaction losses from investors", "2016 scale-back too late — too much capital consumed during loss-amplifying expansion", "Pivot to B2B customers couldn't generate sufficient volume to rebuild company"]),
    aiTags: JSON.stringify(["Cash flow", "Execution"]),
    aiVerdict: "Shyp is a case study in the difference between growth and health. The company's expansion looked like success and was actually loss amplification. The 2016 public letter from the CEO was an unusually honest acknowledgment of the mistake — but came after the capital that would have funded the correction had already been spent.",
  },
];

async function main() {
  console.log("🌱 Seeding database with startup postmortems...\n");

  // Clear existing data
  await prisma.startup.deleteMany();
  await prisma.user.deleteMany();

  // Create a system user for all seeded entries
  const systemUser = await prisma.user.create({
    data: {
      email: "founders@founderautopsy.com",
      password: "$2b$10$seededSystemUserNotForLogin",
    },
  });

  console.log(`✅ Created system user: ${systemUser.email}\n`);

  for (const startup of startups) {
    const created = await prisma.startup.create({
      data: {
        ...startup,
        submittedBy: systemUser.id,
      },
    });
    console.log(`✅ ${created.name} (${created.foundedYear}–${created.closedYear}) — ${created.industry}`);
  }

  console.log(`\n🎉 Seeding complete! ${startups.length} startup postmortems loaded.\n`);
  console.log("Startups by failure category:");
  const tagCounts: Record<string, number> = {};
  for (const s of startups) {
    const tags = JSON.parse(s.aiTags) as string[];
    for (const tag of tags) {
      tagCounts[tag] = (tagCounts[tag] || 0) + 1;
    }
  }
  for (const [tag, count] of Object.entries(tagCounts).sort((a, b) => b[1] - a[1])) {
    console.log(`  ${tag}: ${count}`);
  }
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
